=== cash2one/ionic/hsbank_cms/resources/api/config/function.xsd
<?xml version="1.0"?>


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="class" type="xs:string" />
 <xs:element name="method" type="xs:string"/>
 <xs:element name="type" type="xs:string"/>
 <xs:element name="return" type="xs:string"/>

<xs:element name="params">
 <xs:complexType>
  <xs:sequence>
   <xs:element ref="type"/>
  </xs:sequence>
 </xs:complexType>
</xs:element>

<!-- 复合元素的定义 -->
<xs:element name="function">
 <xs:complexType>
  <xs:sequence  minOccurs="1">
   <xs:element ref="class"  minOccurs="1" maxOccurs="1"/>
   <xs:element ref="method" minOccurs="1" maxOccurs="1"/>
   <xs:element ref="params" minOccurs="1" maxOccurs="1"/>
   <xs:element ref="return" minOccurs="1" maxOccurs="1"/>
  </xs:sequence>
 </xs:complexType>
</xs:element>


<xs:element name="functions">
 <xs:complexType>
  <xs:sequence minOccurs="0" maxOccurs="unbounded">
   <xs:element ref="function"/>
  </xs:sequence>
 </xs:complexType>
</xs:element>


</xs:schema>

=== cash2one/ionic/hsbank_cms/resources/api/functions/function.xml
<?xml version="1.0" encoding="UTF-8"?>
<functions
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../config/function.xsd">

    <function>
        <class>com.thinkgem.jeesite.modules.sys.utils.DictUtils</class>
        <method>getDictLabel</method>
        <params>
            <type>java.lang.String</type>
            <type>java.lang.String</type>
            <type>java.lang.String</type>
        </params>
        <return>java.lang.String</return>
    </function>
    
    <function>
        <class>com.thinkgem.jeesite.common.utils.DateUtils</class>
        <method>formatDateByPattern</method>
        <params>
            <type>java.util.Date</type>
            <type>java.lang.String</type>
        </params>
        <return>java.lang.String</return>
    </function>


    <function>
        <class>com.thinkgem.jeesite.common.utils.StringUtils</class>
        <method>vagueName</method>
        <params>
            <type>java.lang.String</type>
        </params>
        <return>java.lang.String</return>
    </function>

    <function>
        <class>com.thinkgem.jeesite.common.utils.StringUtils</class>
        <method>vagueAccountName</method>
        <params>
            <type>java.lang.String</type>
        </params>
        <return>java.lang.String</return>
    </function>


    <function>
        <class>com.thinkgem.jeesite.modules.api.ApiUtil</class>
        <method>imageUrlConver</method>
        <params>
            <type>java.lang.String</type>
        </params>
        <return>java.lang.String</return>
    </function>



</functions>
